# Generated by Django 3.2.16 on 2022-11-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_auto_20221111_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopingitem',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shopingitem',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
