# Generated by Django 3.2.16 on 2022-11-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_auto_20221111_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopingitem',
            name='item_taken',
            field=models.IntegerField(choices=[(0, 'Not taken'), (1, 'Taken')], default=0),
        ),
    ]
