# Generated by Django 3.2.16 on 2022-11-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0004_shopingitem_item_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopingitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_list.addcategory'),
        ),
        migrations.AlterField(
            model_name='shopingitem',
            name='brand',
            field=models.CharField(max_length=50),
        ),
    ]
