# Generated by Django 3.2.16 on 2022-11-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0005_auto_20221111_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopingitem',
            options={'ordering': ['category']},
        ),
    ]
