# Generated by Django 3.2.16 on 2022-11-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0007_alter_shopingitem_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopingItem',
            new_name='ShoppingItem',
        ),
    ]
