# Generated by Django 3.2.16 on 2022-11-15 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_list', '0013_auto_20221114_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingitem',
            options={'ordering': ['category']},
        ),
        migrations.AddField(
            model_name='addcategory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
