# Generated by Django 3.2.16 on 2022-11-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0020_alter_shoppingitem_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addcategory',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='addcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='addcategory',
            name='name',
            field=models.CharField(default='Enter category Name', max_length=50),
        ),
    ]
