# Generated by Django 3.2.16 on 2022-11-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0021_auto_20221115_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addcategory',
            options={'ordering': ['category']},
        ),
        migrations.RenameField(
            model_name='addcategory',
            old_name='name',
            new_name='category',
        ),
    ]
