# Generated by Django 3.2.16 on 2022-11-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0022_auto_20221115_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcategory',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
