# Generated by Django 3.2.16 on 2022-11-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0023_alter_addcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcategory',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='quantity',
            field=models.CharField(blank=True, default='ex 1 kg', max_length=50),
        ),
    ]
