# Generated by Django 3.2.16 on 2022-11-23 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0024_auto_20221123_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_list.addcategory'),
        ),
    ]
