# Generated by Django 3.2.16 on 2022-11-24 20:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_list', '0025_alter_shoppingitem_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='shoppingitem',
            old_name='taken',
            new_name='picked',
        ),
    ]
