# Generated by Django 3.2.16 on 2022-11-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0027_alter_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingitem',
            old_name='name',
            new_name='item',
        ),
    ]
